// In-memory storage for problematic ingredients
const problematicIngredients = [
    { name: 'oleic acid', reason: 'May increase skin cell turnover, potentially exacerbating flaking' },
    { name: 'olive oil', reason: 'Contains oleic acid, which may worsen symptoms' },
    { name: 'avocado oil', reason: 'High in oleic acid, potentially irritating' },
    { name: 'lanolin', reason: 'Can cause allergic reactions in some individuals' },
    { name: 'mineral oil', reason: 'May trap heat and moisture, creating an environment for yeast growth' },
    { name: 'coconut oil', reason: 'Contains fatty acids that can feed Malassezia yeast' },
    { name: 'soybean oil', reason: 'Contains fatty acids that can feed Malassezia yeast' },
    { name: 'sesame oil', reason: 'Contains fatty acids that can feed Malassezia yeast' },
    { name: 'peanut oil', reason: 'Contains fatty acids that can feed Malassezia yeast' },
    { name: 'wheat germ oil', reason: 'Contains fatty acids that can feed Malassezia yeast' },
    { name: 'corn oil', reason: 'Contains fatty acids that can feed Malassezia yeast' },
    { name: 'linoleic acid', reason: 'Can be metabolized by Malassezia, potentially worsening symptoms' },
    { name: 'polysorbates (e.g., polysorbate 20, 60, 80)', reason: 'Can feed Malassezia yeast' },
    { name: 'esters (e.g., isopropyl myristate, isopropyl palmitate)', reason: 'Can feed Malassezia yeast' },
    { name: 'fatty alcohols (e.g., cetyl alcohol, stearyl alcohol)', reason: 'Can feed Malassezia yeast' },
    { name: 'sorbitan oleate', reason: 'Can feed Malassezia yeast' },
    { name: 'glyceryl stearate', reason: 'Can feed Malassezia yeast' },
    { name: 'oleyl alcohol', reason: 'Can feed Malassezia yeast' },
    { name: 'butylene glycol', reason: 'Can feed Malassezia yeast' },
    { name: 'sorbitol', reason: 'Can feed Malassezia yeast' },
    { name: 'beeswax', reason: 'Can create a barrier that traps moisture and heat, promoting yeast growth' },
    { name: 'cholesterol', reason: 'Can be used by Malassezia yeast' },
    { name: 'ethoxylated ingredients (e.g., PEGs)', reason: 'Can feed Malassezia yeast' },
    { name: 'lauric acid', reason: 'Can be metabolized by Malassezia, potentially worsening symptoms' },
    { name: 'palmitic acid', reason: 'Can be metabolized by Malassezia, potentially worsening symptoms' },
    { name: 'myristic acid', reason: 'Can be metabolized by Malassezia, potentially worsening symptoms' },
    { name: 'stearic acid', reason: 'Can be metabolized by Malassezia, potentially worsening symptoms' },
    { name: 'caprylic/capric triglyceride', reason: 'Can feed Malassezia yeast' },
    { name: 'triolein', reason: 'Can feed Malassezia yeast' },
    { name: 'shea butter', reason: 'Contains fatty acids that can feed Malassezia yeast' },
    { name: 'squalane', reason: 'Can feed Malassezia yeast' },
    { name: 'castor oil', reason: 'Can feed Malassezia yeast' },
    { name: 'jojoba oil', reason: 'Can feed Malassezia yeast' },
    { name: 'grape seed oil', reason: 'Can feed Malassezia yeast' },
    { name: 'rice bran oil', reason: 'Can feed Malassezia yeast' },
    { name: 'sweet almond oil', reason: 'Can feed Malassezia yeast' },
    { name: 'evening primrose oil', reason: 'Can feed Malassezia yeast' },
    { name: 'borage oil', reason: 'Can feed Malassezia yeast' },
    { name: 'sunflower oil', reason: 'Can feed Malassezia yeast' },
    { name: 'macadamia oil', reason: 'Can feed Malassezia yeast' },
    { name: 'argan oil', reason: 'Rich in oleic acid, can feed Malassezia yeast' },
    { name: 'marula oil', reason: 'High in oleic acid, potentially problematic for Malassezia' },
    { name: 'safflower oil', reason: 'Can feed Malassezia yeast, especially high-oleic varieties' },
    { name: 'cocoa butter', reason: 'Can create an occlusive barrier, promoting yeast growth' },
    { name: 'mango butter', reason: 'May be comedogenic and feed Malassezia yeast' },
    { name: 'palm oil', reason: 'Contains fatty acids that can feed Malassezia yeast' },
    { name: 'hydrogenated vegetable oil', reason: 'Can create an occlusive barrier and feed yeast' },
    { name: 'petrolatum', reason: 'Can create an occlusive barrier, trapping moisture and heat' },
    { name: 'dimethicone', reason: 'Can trap moisture and potentially exacerbate symptoms' },
    { name: 'lanolin alcohol', reason: 'Can cause allergic reactions and feed Malassezia' },
    { name: 'cetearyl alcohol', reason: 'A fatty alcohol that can feed Malassezia yeast' },
    { name: 'stearyl alcohol', reason: 'A fatty alcohol that can feed Malassezia yeast' },
    { name: 'cetyl alcohol', reason: 'A fatty alcohol that can feed Malassezia yeast' },
    { name: 'propylene glycol', reason: 'Can potentially irritate sensitive skin' },
    { name: 'glycerin', reason: 'In high concentrations, can feed Malassezia yeast' },
    { name: 'ethylhexyl palmitate', reason: 'An ester that can feed Malassezia yeast' },
    { name: 'isononyl isononanoate', reason: 'An ester that can feed Malassezia yeast' },
    { name: 'myristyl myristate', reason: 'An ester that can feed Malassezia yeast' },
    { name: 'PEG-40 hydrogenated castor oil', reason: 'Can feed Malassezia yeast' },
    { name: 'PEG-100 stearate', reason: 'Can feed Malassezia yeast' },
    { name: 'steareth-20', reason: 'Can feed Malassezia yeast' },
    { name: 'ceteareth-20', reason: 'Can feed Malassezia yeast' },
    { name: 'isopropyl myristate', reason: 'Can feed Malassezia yeast and increase skin cell turnover' },
    { name: 'behenic acid', reason: 'Can be metabolized by Malassezia, potentially worsening symptoms' },
    { name: 'arachidic acid', reason: 'Can be metabolized by Malassezia, potentially worsening symptoms' },
    { name: 'lignoceric acid', reason: 'Can be metabolized by Malassezia, potentially worsening symptoms' },
    { name: 'ceramide 3', reason: 'Can potentially feed Malassezia yeast' },
    { name: 'cholesteryl oleate', reason: 'Can be used by Malassezia yeast' },
    { name: 'ozokerite', reason: 'Can create an occlusive barrier, promoting yeast growth' },
    { name: 'paraffin', reason: 'Can create an occlusive barrier, trapping moisture and heat' }
  ];


  module.exports = problematicIngredients;